var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(info)/about/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mgeqj2._.js")
R.c("server/chunks/ssr/_0kutkqx._.js")
R.c("server/chunks/ssr/19xk_next_dist_esm_build_templates_app-page_0cj75df.js")
R.c("server/chunks/ssr/[root-of-the-server]__1zi5n4y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1692o4_._.js")
R.c("server/chunks/ssr/frontend_src_0bor8we._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_04ow902._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_forbidden_0vfxd_t.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_unauthorized_098p3j3.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_global-error_0b1_q4t.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_(info)_about_page_actions_1sz3nmr.js")
R.m(47716)
module.exports=R.m(47716).exports
